### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by sojusnik** [turtl/firefox-bookmarker#1]
The link to the [extension documentation](https://turtl.it/docs/clients/extensions/index) from the readme.md isn't working.

How to install this plugin and will it work with Firefox 43.0?

**Comment by orthecreedence** [comment]
Sorry, Mozilla canned the old version of the bookmarker addon and I haven't had time to re-build and re-submit it with the new SDK. I will try to get this up in the next few days. Tracked: https://trello.com/c/XXeSPQdu
