### ISSUE TITLE
Make keybaord shortcuts configurable.

### ISSUE THREAD

**Issue by abhinandh** [turtl/firefox-bookmarker#2]
I installed the firefox extension and was browsing my RSS feeds with tt-rss. Looks like tt-rss and turtl have both mapped the same shortcut, Ctrl + ↓, which makes it rather unpleasant to use both together. 

Ideally the keybinding should be configurable.

**Comment by orthecreedence** [comment]
This is a great idea. I've tracked this on our main issue tracker (https://trello.com/c/zhgLooMV) so I'm going to close this on Github. Thanks for the feedback!
